### ISSUE TITLE
default config/database.yml causes heroku app crash

### ISSUE THREAD

**Issue by guava-mc** [railstutorial/first_app#2]
## Expected Behavior
Following the [online rails tutorial](https://www.railstutorial.org/book/beginning#sec-heroku_setup) the `hello_app` should be visible on the deployed heroku site.

## Actual Behavior
`hello_app` crashes with [specification](#Specifications), error: `Error Loading the 'sqlite3' Active Recored adapter. Missing gem it depends on? sqlite3 is not part of the bundle. Add it to your Gemfile. (LoadError)`

## Steps to Reproduce the Problem

  1. Using [specification](#Specifications) follow the `hello_app` tutorial up to and including [heroku_setup](https://www.railstutorial.org/book/beginning#sec-heroku_setup)
  2. check `heroku logs --tail` to see `App Crash`
  3. verify error with `heroku run rails console`

## Specifications

  - Rails: 6.0.3
  - ruby: 2.6.6
  - heroku: 7.41.1
  - OS: Xubuntu 

## Solution
Modify config/database.yml production mapping:
```yaml
# Postgresql config for Heroku
production:
  adapter: postgresql
  database: production_postgres
  pool: 5
  username: hello_postgres
  password: 
```

**Comment by mhartl** [comment]
Thanks for your message. The “first app” here is actually from a previous version of the tutorial, so it should probably be deleted, but before doing that I wanted to address your helpfully detailed report. (This assumes that you’re only commenting here and not using the code; if you *are* using the code here, you should instead use the code in the current version of the book. Since you linked to the current version, my guess is that this was simply a convenient place to leave the report.)

The steps in Chapter 1 of the Rails Tutorial have been heavily debugged, and experience shows that errors in Heroku deployments are generally the result of some small discrepancy between the steps performed and the steps as written. In particular, as noted in [Listing 1.6](https://www.railstutorial.org/book/beginning#code-gemfile_sqlite_version) and again in [Section 1.4.1](https://www.railstutorial.org/book/beginning#sec-heroku_setup), it is essential to list the `sqlite3` gem only in the development and test environments of the `Gemfile`, and not in production. Accidentally leaving it in production (or unscoped by environment) could account for the behavior you observed.

I suggest retracing your steps to make sure that the above `sqlite3` steps have been completed (together with a `bundle install --without production` as in [Listing 1.19](https://www.railstutorial.org/book/beginning#code-bundle_without_production)). If you still believe there is an error in the tutorial, please share a GitHub repo of an app that reproduces the issue. If I am able to reproduce it myself, I will correct it ASAP.

**Comment by guava-mc** [comment]
I apologize for reporting the issue here--I looked on the website for a place to report issues but did not find anything (sorry if I missed it!). I thought this would be the next best way to share it in case it was deemed worthy of further investigation.

To the best of my knowledge, I followed all the steps outlined in your reply and procedurally stepped through chapter one. I went back through my `history` to verify while debugging that I did not miss one of the steps and checked my Gemfile multiple times. 

Of course, I still definitely could have made a mistake. 😅 

Here is my Gemfile and the config/database.yml before I made the same proposed change in #3.

Happy to share my repo if needed once I get back to the computer.

Thank you so much for your work, I only shared in hopes that I could be of some small help. Very excited to continue on this journey learning Rails!
 
##### Gemfile
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'rails', '6.0.3'
gem 'puma', '4.3.3'
gem 'sass-rails', '5.1.0'
gem 'webpacker', '4.0.7'
gem 'turbolinks', '5.2.0'
gem 'jbuilder', '2.9.1'
gem 'bootsnap', '1.4.5', require: false

group :development, :test do
  gem 'sqlite3', '1.4.1'
  gem 'byebug', '11.0.1', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '4.0.1'
  gem 'listen', '3.1.5'
  gem 'spring', '2.1.0'
  gem 'spring-watcher-listen', '2.0.1'
end

group :test do
  gem 'capybara', '>= 2.15', '3.28.0'
  gem 'selenium-webdriver', '3.142.4' 
  gem 'webdrivers', '4.1.2'
end

group :production do
  gem 'pg', '1.1.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

##### Original config/database.yml
```yaml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```
